name: CI - Lint and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['20']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Clean install dependencies
        run: |
          npm ci --no-audit --no-fund
          npm rebuild  # Пересборка native модулей если есть

      - name: Setup Husky
        run: |
          # Явная установка прав для husky
          git config --global --add safe.directory /github/workspace
          npm run prepare || true
          chmod -R +x .husky/ || true

      - name: Verify Node environment
        run: |
          node -v
          npm -v
          npx husky --version || echo "Husky not available"

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx --max-warnings=0

      - name: Run tests with coverage
        run: |
          npm test -- --coverage
          echo "Test results:"
          cat coverage/lcov.info | grep -E '^(LF|LH)' || true

      - name: Upload coverage to Codecov (optional)
        if: success()
        uses: codecov/codecov-action@v4